# Generated by Django 3.0.5 on 2020-05-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200507_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the blog', max_length=100),
        ),
    ]
